### ISSUE TITLE
Could you output the High Quality Transit Corridors as lines as well?

### ISSUE THREAD

**Issue by aickin** [BayAreaMetro/Data-And-Visualization-Projects#2]
Hi there! I've been making a map over the last week or so to document the potential impact of SB 827, and I have a feature request for the High Quality Transit Corridors. Is there any way you could output the HQTCs as just line strings? The quarter and half mile buffer versions are great, but I'd love to be able to try other scenarios out for visualization, and I'm happy to buffer the lines myself. Thanks!!

**Comment by tbdv** [comment]
see https://github.com/BayAreaMetro/Data-And-Visualization-Projects/issues/1
